config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    member do
      put 'like'
    end
  end
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :author, length: { minimum: 4 }
  validates :content, length: { in: 4..280 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def hello
    render html: "<h1>It works WASLAB05!</h1>".html_safe
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :like]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all().sort_by{ |h| h.created_at }.reverse
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { redirect_to tweets_url, alert: @tweet.errors.full_messages  }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
    (session[:current_user_id] ||= []) << Array(:current_user_id) unless session.include?(:current_user_id)
    session[:current_user_id].push(@tweet.id)
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    if session[:current_user_id].include?(@tweet.id)
      @tweet.destroy
      session[:current_user_id].delete(@tweet.id)
      respond_to do |format|
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to tweets_url, alert: 'You are not allowed to delete this tweet' }
        format.json { head :Forbidden }
      end
    end
  end
  
  # PUT /tweet/1/like
  def like
    @tweet.likes += 1
    @tweet.save
    respond_to do |format|
        format.html { redirect_to tweets_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waslab05</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
 <body class="wotbody">
<h1 class="wottitle">Wall of Tweets - RoR Edition</h1>
<br/>

<div class="walltweet">
<form action="/tweets" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="SYOMa4udDV173VRKKX0QDids+Po7krwXrUHG9kte79K+LSFOJzU9IhBl4tDzK1f9/Hb1zRFsZHuQ5kcPSAvfTg==" />
<table border=0 cellpadding=2>
<tr><td>Your name:</td><td><input size="70" type="text" name="tweet[author]" id="tweet_author" /></td><td/></tr>
<tr><td>Your tweet:</td><td><textarea rows="2" cols="70" name="tweet[content]" id="tweet_content">
</textarea></td>
<td><input type="submit" name="commit" value="Tweet!" data-disable-with="Tweet!" /></td></tr>
</table>
</form></div>
<%if notice != nil%>
        <div class="wotitem" id="notice">
          <%= notice %>
        </div>
<%end%>
<%if alert != nil%>
    <div class="wotitem" id="alert">
      <% if alert.kind_of?(Array) %>
        <% @n = alert.size %>
        <% for i in 0..@n %>
          <%= alert[i] %>
          <% if i < @n-2 %>
            ,
          <% elsif i == @n-2 %>
            and
          <% end %>
        <% end %>
      <% else %>
        <%= alert %>
      <%end%>
    </div>
<%end%>

   
    <% @data = nil %> 
    <% @tweets.each do |tweet| %>
      <tr>
        <% if @data != tweet.created_at.strftime("%d/%m/%Y") %>
          <% @data = tweet.created_at.strftime("%d/%m/%Y") %>
          <br><h3>...... <%= @data %></h3>
        <% end %>
        <div class="wotitem" id="<%= tweet.id %>">
    <div class="likes">
    <span class="numlikes" id='showLikes_<%= tweet.id %>'><%= tweet.likes%></span><br/><span class="smallfont">people like this<span><br/>
    <h3><a rel="nofollow" data-method="put" href="/tweets/<%= tweet.id %>/like">like</a></h3>
    </div>
    <div class="item">
    <h4><em><%= tweet.author %></em> @ <%= tweet.created_at.strftime("%H:%M") %></h4>
    <p><%= tweet.content %></p>
    <p style="text-align: right;"><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/tweets/<%= tweet.id %>" >Destroy</a></p>
    </div>
  </div>
      </tr>
    <% end %>
  </body>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @tweet.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>